---
docker_version: '18.06'
docker_selinux_version: '17.03'

docker_package_info:
  pkgs:

docker_repo_key_info:
  repo_keys:

docker_repo_info:
  repos:

docker_dns_servers_strict: true

docker_container_storage_setup: false

# Used to override obsoletes=0
yum_conf: /etc/yum.conf
yum_repo_dir: /etc/yum.repos.d
docker_yum_conf: /etc/yum_docker.conf

docker_mirror: https://download.docker.com

# Fedora docker-ce repo
docker_fedora_repo_base_url: "{{ docker_mirror }}/linux/fedora/$releasever/$basearch/stable"
docker_fedora_repo_gpgkey: "{{ docker_mirror }}/linux/fedora/gpg"
# CentOS/RedHat docker-ce repo
docker_rh_repo_base_url: "{{ docker_mirror }}/linux/centos/7/$basearch/stable"
docker_rh_repo_gpgkey: "{{ docker_mirror }}/linux/centos/gpg"
# Ubuntu docker-ce repo
docker_ubuntu_repo_base_url: "{{ docker_mirror }}/linux/ubuntu"
docker_ubuntu_repo_gpgkey: "{{ docker_mirror }}/linux/ubuntu/gpg"
# Debian docker-ce repo
docker_debian_repo_base_url: "{{ docker_mirror }}/linux/debian"
docker_debian_repo_gpgkey: "{{ docker_mirror }}/linux/debian/gpg"
docker_bin_dir: "/usr/bin"

# flag to enable/disable docker cleanup
docker_orphan_clean_up: false
